version: '3.8'
services:
  pgdb:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=employeedb
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
    restart: always
volumes:
  data:
    driver: local